import type { ModelInfo } from "../model.js"

export type AetherapiModelId = keyof typeof aetherapiModels

export const aetherapiDefaultModelId: AetherapiModelId = "kimi-k2.6"

export const aetherapiModels = {
	"kimi-k2.6": {
		maxTokens: 8192,
		contextWindow: 262_144,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.42,
		outputPrice: 1.96,
		description:
			"Kimi K2.6 is a state-of-the-art multimodal language model with vision and tool calling capabilities, featuring a 262K context window.",
	},
	"claude-opus-4-7": {
		maxTokens: 128_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 3.5,
		outputPrice: 17.5,
		cacheWritesPrice: 3.5,
		cacheReadsPrice: 0.5,
		supportsReasoningBudget: true,
		description:
			"Claude Opus 4.7 — Anthropic's most capable model with 200K context window, advanced reasoning, and agentic capabilities.",
	},
	"claude-opus-4-6": {
		maxTokens: 128_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 3.5,
		outputPrice: 17.5,
		cacheWritesPrice: 3.5,
		cacheReadsPrice: 0.5,
		supportsReasoningBudget: true,
		description:
			"Claude Opus 4.6 — Anthropic's high-capability model with exceptional reasoning, coding, and agentic performance.",
	},
	"claude-sonnet-4-6": {
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 2.1,
		outputPrice: 10.5,
		cacheWritesPrice: 2.1,
		cacheReadsPrice: 0.3,
		supportsReasoningBudget: true,
		description:
			"Claude Sonnet 4.6 — Anthropic's balanced model with strong reasoning, vision, and tool calling at efficient pricing.",
	},
	"gpt-5.5": {
		maxTokens: 128_000,
		contextWindow: 1_050_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["none", "low", "medium", "high", "xhigh"],
		reasoningEffort: "none",
		inputPrice: 3.5,
		outputPrice: 21.0,
		cacheReadsPrice: 0.3,
		supportsTemperature: true,
		description:
			"GPT-5.5 — OpenAI's advanced multimodal model with 1M+ context, vision, and configurable reasoning effort.",
	},
	"gpt-5.4": {
		maxTokens: 128_000,
		contextWindow: 1_000_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["none", "low", "medium", "high", "xhigh"],
		reasoningEffort: "none",
		inputPrice: 1.7,
		outputPrice: 10.0,
		cacheReadsPrice: 0.25,
		supportsTemperature: true,
		description:
			"GPT-5.4 — OpenAI's powerful multimodal model with 1M context window, vision support, and reasoning capabilities.",
	},
	"gpt-5.4-mini": {
		maxTokens: 128_000,
		contextWindow: 400_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["none", "low", "medium", "high", "xhigh"],
		reasoningEffort: "none",
		inputPrice: 0.5,
		outputPrice: 3.0,
		cacheReadsPrice: 0.075,
		supportsTemperature: true,
		description:
			"GPT-5.4 Mini — Cost-efficient variant of GPT-5.4 with strong performance and 400K context window.",
	},
	"gpt-5.4-nano": {
		maxTokens: 128_000,
		contextWindow: 400_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["none", "low", "medium", "high", "xhigh"],
		reasoningEffort: "none",
		inputPrice: 0.14,
		outputPrice: 0.84,
		cacheReadsPrice: 0.02,
		supportsTemperature: true,
		description:
			"GPT-5.4 Nano — Ultra-fast, cost-effective model for lightweight tasks with 400K context window.",
	},
	"gpt-4.1": {
		maxTokens: 32_768,
		contextWindow: 1_047_576,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 1.4,
		outputPrice: 5.6,
		cacheReadsPrice: 0.5,
		supportsTemperature: true,
		description:
			"GPT-4.1 — OpenAI's reliable multimodal model with 1M context window and strong tool calling.",
	},
	"gpt-4.1-mini": {
		maxTokens: 32_768,
		contextWindow: 1_047_576,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 0.28,
		outputPrice: 1.12,
		cacheReadsPrice: 0.1,
		supportsTemperature: true,
		description:
			"GPT-4.1 Mini — Efficient variant of GPT-4.1 with 1M context and excellent cost-performance.",
	},
	"qwen3.6-plus": {
		maxTokens: 65_536,
		contextWindow: 262_144,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.5,
		outputPrice: 2.1,
		description:
			"Qwen 3.6 Plus — Alibaba's high-performance coding and reasoning model with 262K context window.",
	},
	"deepseek-v4-flash": {
		maxTokens: 384_000,
		contextWindow: 1_047_576,
		supportsImages: false,
		supportsPromptCache: true,
		supportsReasoningEffort: ["disable", "low", "medium", "high", "xhigh"],
		preserveReasoning: true,
		reasoningEffort: "high",
		inputPrice: 0.1,
		outputPrice: 0.19,
		cacheWritesPrice: 0.1,
		cacheReadsPrice: 0.028,
		description:
			"DeepSeek V4 Flash — Ultra-fast reasoning model with 1M context and efficient MoE architecture.",
	},
	"deepseek-v4-pro": {
		maxTokens: 384_000,
		contextWindow: 1_047_576,
		supportsImages: false,
		supportsPromptCache: true,
		supportsReasoningEffort: ["disable", "low", "medium", "high", "xhigh"],
		preserveReasoning: true,
		reasoningEffort: "high",
		inputPrice: 0.304,
		outputPrice: 0.6,
		cacheWritesPrice: 0.304,
		cacheReadsPrice: 0.087,
		description:
			"DeepSeek V4 Pro — Full-capability reasoning model with 1M context and advanced agentic performance.",
	},
	"minimax-m2.7": {
		maxTokens: 16_384,
		contextWindow: 204_800,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.21,
		outputPrice: 0.84,
		cacheWritesPrice: 0.21,
		preserveReasoning: true,
		description:
			"MiniMax M2.7 — Agent-optimized model with recursive self-improvement and strong coding capabilities.",
	},
	"minimax-m2.5": {
		maxTokens: 16_384,
		contextWindow: 204_800,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.21,
		outputPrice: 0.84,
		cacheWritesPrice: 0.21,
		preserveReasoning: true,
		description:
			"MiniMax M2.5 — Balanced agentic model with enhanced coding and cost-effective performance.",
	},
	"glm-5.1": {
		maxTokens: 131_072,
		contextWindow: 202_752,
		supportsImages: false,
		supportsPromptCache: true,
		supportsReasoningEffort: ["disable", "medium"],
		reasoningEffort: "medium",
		preserveReasoning: true,
		inputPrice: 1.1,
		outputPrice: 3.5,
		cacheWritesPrice: 0,
		description:
			"GLM-5.1 — Z.AI's most capable model with 202K context, 128K max output, and built-in thinking capabilities.",
	},
} as const satisfies Record<string, ModelInfo>
