version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directories:
      - "/"
      - "/apps/*"
      - "/packages/*"
      - "/src"
      - "/webview-ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
        group-by: "dependency-name"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        group-by: "dependency-name"
