export { detectWorkspace } from "./detection"
export type { WorkspaceState } from "./detection"
export { readManifest, writeManifest } from "./manifest"
export type { BooManifest, BooManifestFrontmatter, PillarOverrides } from "./manifest"
export { resolvePillars } from "./pillars"
export type { ResolvedPillars } from "./pillars"
export { discoverComponents } from "./components"
export type { DiscoveredComponent } from "./components"
export { initWorkspace, ensureAgentsFile } from "./init"
export type { GenerateDescription } from "./init"
